### ISSUE TITLE
my-comment.yml problem

### ISSUE THREAD

**Issue by jsbien** [UniversalViewer/uv-app-starter#10]
Is the description of  custom annotations presented at https://github.com/edsilv/biiif/#annotations valid for uv-app-starter? I get
`unable to determine type of collection/ParkoszPWN/_01/my-comment.yml`

**Comment by edsilv** [comment]
I'm not seeing that file in your repo - could you post the contents here?

**Comment by jsbien** [comment]
I answered by mail (at least I tried) but repeat it here:

I made an experiment with the example from
https://github.com/edsilv/biiif/, i.e.

`motivation: commenting`
`value: This is my comment on the image`

It's not in my the repo because it breaks the processing.

**Comment by edsilv** [comment]
Check the generated index.json - the annotation should be there. It's just letting you know that you haven't specified a `type` for your annotation body. Try adding `type: Text`. That's enough info for biiif to guess a `format` of `text/plain`.
