### ISSUE TITLE
Document biiif conventions in more detail

### ISSUE THREAD

**Issue by nichtich** [UniversalViewer/uv-app-starter#12]
The link to [biiif conventions](https://github.com/edsilv/biiif/#examples) shows examples but not specification how to organize files. For instance it's unclear to me whether to put metadata in JSON or in YAML files. Is metadata mandatory and if so which fields? Some more details would help.

**Comment by edsilv** [comment]
Hi, metadata is not mandatory, but can be included as an `info.yml` file within a collection, manifest, or canvas folder. Here's an example of an `info.yml` supplying descriptive + rights properties and metadata for a `gold-broach` manifest: 

https://github.com/nomadproject/objects/blob/gh-pages/collection/gold-broach/info.yml

This manifest contains a single canvas folder `_gold-broach` with an image to be painted onto the canvas. If there were many canvases in this manifest it might make sense to add an `info.yml` to each subfolder with extra image-specific metadata.

Within the `info.yml` you can set the `label`, `description`, and `attribution` descriptive and rights properties at the top-level. IIIF Presentation 3 has renamed `description` to `summary`, and `attribution` to `requiredStatement` but these will still work in IIIF viewers: https://iiif.io/api/presentation/3.0/#appendices I'll update them asap (presentation 3 is still in beta).

Under these you can add a `metadata` section that is essentially a list of key value pairs containing any info you like (there is deliberately no specification for this as the IIIF spec writers feel it falls outside of their remit).

Right now I link to a few example projects using biiif, but you're absolutely right that there needs to be better documentation. I'll add an issue for that and to test the new presentation 3 properties.
