### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by minusdavid** [UniversalViewer/uv-app-starter#2]
I resolved the line ending issue using find and dos2unix, but now I'm seeing "SyntaxError: Unexpected token function". I'm running node 6.11.1 (from a package manager) but it looks like "async function" requires at least Node 7.6 (https://stackoverflow.com/questions/37815790/syntaxerror-unexpected-token-function-async-await-nodejs).

You should probably add an "engines" key to your package.json so that people can know that it won't work on anything older than 7.6 at the outset (https://docs.npmjs.com/files/package.json#engines).

**Comment by minusdavid** [comment]
Used nvm (https://github.com/creationix/nvm/blob/master/README.md) to install Node 9.5.0 and that got me through the process with no errors and the HTTP server started listening.

**Comment by edsilv** [comment]
Hi, sorry I missed this - glad you got it sorted! I've now added the same `engines` section as biiif.

Could perhaps add a `gitattributes` with `* text=auto` as per http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/ to enforce `LF` line endings too?

**Comment by minusdavid** [comment]
Thanks for adding the engines section!

Hmm, good question. Might be worth a try.
