### ISSUE TITLE
Supplying own manifest doesn't work

### ISSUE THREAD

**Issue by minusdavid** [UniversalViewer/uv-app-starter#5]
So I'm trying to cheat a bit... I don't want to use biiif. Instead, I've put together my own manifest, but for some reason the UV app via uv-app-starter is rewriting the IP address in the manifest URIs to localhost... and I have no idea. Combing through UV and OpenSeaDragon and I haven't yet seen where it's happening... but it's driving me a little crazy.

I'll have to keep digging more tomorrow...

**Comment by edsilv** [comment]
I think you need to change the URL attribute of the `<iiif-gallery>` tag in
index.html

**Comment by minusdavid** [comment]
Thanks for the suggestion, but unfortunately changing it to be fully qualified has made no difference :(. 

If I go to the manifest directly, the URLs all have the correct IP address, but in the console it is showing localhost instead of the IP address. I guess I need to keep hunting.

**Comment by minusdavid** [comment]
Comparing against a manifest generated using biiif... and I realize that I'm using a v2 manifest instead of a v3 manifest. 

I thought UV support v2 and the in-progress v3?

**Comment by minusdavid** [comment]
I was going to give up and use https://github.com/IIIF/presentation-validator instead, but that tool actually appears to be buggy as well... *sigh*

**Comment by minusdavid** [comment]
I was able to find figure out the bug in presentation-validator though. I'm not sure it's worth my time trying to figure out how to make the Universal Viewer work... which is too bad as I'd really like to see a demo work with a manifest that I create myself that uses a real IIIF image server rather than just a web server using static assets

**Comment by minusdavid** [comment]
Then again... even if my manifest validates... I still want to make sure it will actually work in a IIIF viewer...

**Comment by minusdavid** [comment]
So I'm using O'Sullivan (https://github.com/iiif-prezi/osullivan) to create my manifest, and I've gotten it to validate using https://github.com/IIIF/presentation-validator, but still having this problem of the IP address being rewritten to localhost...

It's 5:05pm now... so I'll have to try chasing this one another day this week.

Actually, I have one more idea to try out...

**Comment by minusdavid** [comment]
Could it be a bug in Manifesto? 

I was just reading your post at http://blog.edsilv.com/manifesto/. 

I was looking through the code and I think it was parsing the manifest JSON just fine... but then there has to be an intervening step somewhere which I have yet to find. 

Looking at the biiif manifest vs the O'Sullivan manifest... the only difference I see is that the former is v3 and the latter is v2 of the IIIF Presentation API? The v2 version is JSON-LD whereas the biiif version just looks like JSON...

It looks like despite validating against the tool my manifest is still a bit inconsistent with the spec... but the observed behaviour just seems so weird still...

**Comment by minusdavid** [comment]
Using console.trace() to get a stacktrace to work backwards from the error...

t.openMedia @ uv.js:formatted:21519 has the data with localhost instead of the IP address.

Another thought I had, rather than digging through the code, was to see if a hostname would work instead of an ip address...

**Comment by minusdavid** [comment]
Hmm nope... that didn't do it. In this case, the hostname is being rewritten to localhost too...

**Comment by minusdavid** [comment]
OK... having the same problem with Mirador.

It can fetch the manifest, parse it, get the title and the thumbnail, but when it tries to load the tiles... it uses localhost instead of the hostname or IP address to try to do the fetch. Since it's happening UV and Mirador... there must be something wrong with my manifest? 

That said, the stacktrace in Mirador looks almost the same as the stacktrace in UV...

**Comment by minusdavid** [comment]
OK... I made a service @id which would never ever resolve... and now it's not rewriting the domain. I'm thinking this might be an issue with my server...

**Comment by minusdavid** [comment]
Hmm then again... changed the network setting that I thought might be affect it but nope. Still rewriting...

**Comment by minusdavid** [comment]
Ahh unless... maybe it's Loris and Apache...

**Comment by minusdavid** [comment]
Hmm no... nothing to do with Apache or Loris. They're not being accessed at all...

**Comment by minusdavid** [comment]
Mirador is using the service @id property to fetch a thumbnail for its list view... so it's working fine at that stage...

**Comment by minusdavid** [comment]
If I sabotage that value by changing it to https from http... it doesn't rewrite..

**Comment by minusdavid** [comment]
It seems to be something specific to the viewer... maybe OpenSeaDragon specifically if it's happening in both UV and Mirador..

**Comment by minusdavid** [comment]
Well that was bloody random... suddenly it just started to work in Mirador...

**Comment by minusdavid** [comment]
Ahh.. the thumbnail loaded for the first time, but clicked on that and broken again...

**Comment by minusdavid** [comment]
Yeah it's using the service URL to create thumbnails just fine... most of the manifest is being read fine... but it can't load the image and zoom...

**Comment by minusdavid** [comment]
I feel like this must be "tileSource" related?

**Comment by minusdavid** [comment]
Hmm I don't think it's openseadragon, since in the stacktrace... by the time it gets to that Javascript, it's already passing on a bad URL for the tile source. So it seems like it's something in UV/Mirador...

**Comment by minusdavid** [comment]
Trying the manifesto-simple-demo and it is looking fine. manifesto.loadManifest gets the JSON, manifesto.create(manifest) creates the manifest object. The methods work and everything looks OK...

**Comment by minusdavid** [comment]
Digging through uv.js and it looks like Manifold.loadManifest() is loading things correctly..

**Comment by minusdavid** [comment]
Aha... so this is interesting...

"t.getSequenceByIndex(e.sequenceIndex);" is looking fine.

However, "t.getCanvasByIndex(e.canvasIndex);", it returns an object which has a property "externalResource", which has a "data" property, and its @id does not match the @id of the service in the __jsonld property for the canvas (and its child objects)!

**Comment by minusdavid** [comment]
Sure looks like a Manifesto bug to me... going to dig a bit deeper...

And maybe uv-app-starter works with biiif because it's not using jsonld?

**Comment by minusdavid** [comment]
I'm playing with the Manifesto methods using https://github.com/IIIF-Commons/manifesto-simple-demo but I can't get that externalResource property now...

**Comment by minusdavid** [comment]
Hmm but in uv-app-starter... it's using Manifold rather than Manifesto for loading the manifest?

**Comment by minusdavid** [comment]
Tried nuking the property temporarily but that didn't help as I think the data had already been passed on somewhere else...

**Comment by minusdavid** [comment]
So I deleted the service object out of my image resource and now it's working fine. My canvas.externalResource.data.id is using the correct domain instead of localhost. 

http://iiif.io/api/presentation/2.1/#image-resources 

Hmm if I start screwing around more... like tacking "/info.json" onto the end... I get a 404 because it tries to tack /info.json onto the end. It also has an issue because it's a different domain. I wonder if that's part of my issue...

**Comment by minusdavid** [comment]
Nope... brought it under the same domain and added a proxy and still no luck...

**Comment by minusdavid** [comment]
It's definitely something to do with that service property though. Because if I take it away, the UV works great.

**Comment by minusdavid** [comment]
OK. I think I've found the problem.

I haven't fixed the problem, but I think it's bad data coming back in my info.json from a HEAD request that is done within ExternalResource.prototype.getData(). 

Even though the request wasn't showing up in Apache, I think Loris must be misconfigured. I'll close this issue once I've figured the configuration.

**Comment by minusdavid** [comment]
Ah, the info.json was being cached by Loris and it was using the wrong domain. I must have made a request to Loris using localhost once upon a time for this image and it cached it. Cleared the cache and redid the request using the updated IP address and now it's working great. 

It's a shame that it took me so long to work that out, but at least I have a much much better understanding of how IIIF viewers work!

**Comment by edsilv** [comment]
Just catching up on emails post-uvcon. Glad you found the solution!

On 21 Mar 2018 23:56, "minusdavid" <notifications@github.com> wrote:

Closed #5 <https://github.com/UniversalViewer/uv-app-starter/issues/5>.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/UniversalViewer/uv-app-starter/issues/5#event-1534494760>,
or mute the thread
