### ISSUE TITLE
A fresh install doesn't work

### ISSUE THREAD

**Issue by jsbien** [UniversalViewer/uv-app-starter#7]
For https://github.com/jsbien/jsb-uv-app-starter `npm start` gives
`> biiif collection -u http://localhost:8888/collection`
`/usr/bin/env: ‘node\r’: No such file or directory`

Some time ago I installed already the software without any problems in another directory (more precisely, on a different disk) of the same computer. The old installation works but does not display the collection correctly (perhaps I made some mistake in the collection structure), that why I tried a fresh install. What can be reason of the difference?

**Comment by edsilv** [comment]
Would you mind adding your project to a GitHub repo and sharing with me? I'll clone it and take a look.

**Comment by jsbien** [comment]
I understand my repo https://github.com/jsbien/jsb-uv-app-starter is already public. I will appreciate very much if you try to reproduce the problem. 
The sample data are just for testing the installation, my real goal is several pages of 15th century manuscript but it will take me several days to prepare the real data.

**Comment by edsilv** [comment]
Hi, I've got that working locally. The README.md in the collection folder was causing a build error for me - will look into a fix to ignore .md files. I've also updated biiif and the UV to their latest versions (see uv-app-starter). You can set an upstream on your fork to merge these changes.

For simplicity's sake I've attached a working zipped version of your project too. Hope this helps!
[jsb-uv-app-starter.zip](https://github.com/UniversalViewer/uv-app-starter/files/3124105/jsb-uv-app-starter.zip)

**Comment by jsbien** [comment]
Thank you very much for your quick and very constructive reaction. Unfortunately the version which works on your computer doesn't work on mine, cf. the enclosed log: 
[errorlog.zip](https://github.com/UniversalViewer/uv-app-starter/files/3124260/errorlog.zip)
However in an earlier (81e73d2) version `npm start` correctly starts the server (just the collection is not displayed correctly, maybe my fault).
As an Emacs user I tried M-x ediff-directories on `node_modules` but there are too many differences. Do you have an idea where to look for the culprit?
This is Debian buster updated almost every day. On the other hand my computer recently behaves erratically (I suspect overheating) but in my opinion the described problems occurs too systematically for an harware error.

**Comment by jsbien** [comment]
I cloned the repository and made `git checkout 81e73d2`: looks like the only differences in `node_modules` are the directory names. However `npm start` also gives the very error. I'm totally confused :-(

**Comment by edsilv** [comment]
Just checking your error log and it looks like you're running node v8.1.4
In the package.json it specifies that you need v>=8.9.1. Could you try upgrading to that version (or above) and try again?

**Comment by jsbien** [comment]
On Sun, Apr 28 2019 at  3:42 -07, Edward Silverton wrote:
> Just checking your error log and it looks like you're running node v8.1.4
> In the package.json it specifies that you need v>=8.9.1. Could you try upgrading to that version (or above) and try again?

Tomorrow I will install https://packages.debian.org/buster/nodejs,
i.e. 10.15.2~dfsg-2, and will report the results.

**Comment by jsbien** [comment]
This version of node was already installed but was not used. Instead a version `/home/jsbien/.nvm/versions/node/v8.1.4/bin/node` was used, installed by some other experiment without my knowledge. After renaming the `.nvm` directory your example works - thank you very much.
I don't close the issue yet as I want to analyse the problem more closely (the main question now is why the earlier installation works...).

**Comment by jsbien** [comment]
Earlier installation doesn't work fully correctly but also doesn't throw an error... I'm still curious, but I give up due to more important tasks.

**Comment by jsbien** [comment]
In the `jsb-uv-app-starter.zip` you corrected `index.html` using   `selectManifest` instead of `onSelectManifest` and  `selectCollection` instead of `onSelectCollection`. In my experience the repository version makes the document thumbs not clickable, so it is impossible to select a specific document. Hence it looks like the change should be included in the repository.

**Comment by edsilv** [comment]
the latest version of iiif-gallery (0.0.28) removes the `on` in order to fit with the recommended event naming pattern. Make sure you include iiif-gallery in your head using the correct version number.
