### ISSUE TITLE
This Stencil app is disabled for this browser.

### ISSUE THREAD

**Issue by jsbien** [UniversalViewer/uv-app-starter#8]
Firefox (60.6.1 ESR of March 22, 2019) gives me this message with an explanation I don't understand.

I can live with it using Chrome instead, but it is less convinient.

**Comment by edsilv** [comment]
Ah, darn - sorry about that. I've published a new build of iiif-gallery. Please update to v0.0.28:

https://github.com/UniversalViewer/uv-app-starter/blob/gh-pages/index.html#L12

I've also added a `prepublishOnly` script to iiif-gallery to ensure this doesn't happen again.
